[package]
name = "oxide"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["cargo", "derive"] }
clap_complete = "3.0.2"
