[package]
name = "oxide"
version = "0.1.0-pre.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "^0.12.1"
anyhow = "1"
async-trait = "^0.1.52"
atty = "^0.2.14"
chrono = { version = "^0.4", features = ["serde"] }
chrono-humanize = "^0.2.1"
#clap = { version = "^3.0.6", features = ["cargo", "derive", "env", "unicode"] }
# Fix once https://github.com/clap-rs/clap/pull/3174 is merged.
clap = { git = "https://github.com/sondr3/clap", branch = "generate-man", features = ["cargo", "derive", "env", "unicode"] }
#clap_complete = "^3.0.2"
# Fix once https://github.com/clap-rs/clap/pull/3174 is merged.
clap_generate = { git = "https://github.com/sondr3/clap", branch = "generate-man" }
colored_json = "^2.1.0"
dialoguer = "^0.9.0"
dirs = "4"
heck = "^0.4.0"
http = "^0.2.6"
regex = "1"
open = "^2.0.2"
oxide-api = "0.1.0-rc.14"
pulldown-cmark = "^0.9.1"
pulldown-cmark-to-cmark = "^9.0.0"
reqwest = { version = "^0.11.9", default-features = false, features = ["json", "rustls-tls"] }
# Fix once https://github.com/clap-rs/clap/pull/3174 is merged.
roff = { git = "https://github.com/sondr3/roff-rs", branch = "updates" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shlex = "^1.1.0"
tabwriter = "^1.2.1"
tempfile = "^3.3.0"
termbg = "^0.4.0"
terminal_size = "^0.1.17"
terminal-spinners = "^0.3.2"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
toml = "^0.5.8"
toml_edit = "^0.13.0"
version-compare = "^0.1.0"

[dev-dependencies]
pretty_assertions = "1"
test-context = "^0.1.3"

# Fix once https://github.com/clap-rs/clap/pull/3174 is merged.
[patch.crates-io]
clap = { git = "https://github.com/sondr3/clap", branch = "generate-man" }
