[package]
name = "cli-macro"
description = "Macro for our CLI generation"
version = "0.1.0"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
cli-macro-impl = { path = "../cli-macro-impl" }

